### ISSUE TITLE
一部のカスタム絵文字をレンダリングできない

### ISSUE THREAD

**Issue by Hayao0819** [yamader/react-mfm#5]
気持ちMastdon系が多め

v13以降の仕様変更の影響もある？

![image](https://github.com/yamader/react-mfm/assets/32128205/d343a56e-3a8b-4a8a-8d55-01c7fd666772)

**Comment by yamader** [comment]
これreact-mfm側の責任じゃない

**Comment by yamader** [comment]
それを使うアプリが各自実装するもの

**Comment by Hayao0819** [comment]
あれま、じゃあこれMinskey側のIssueか

**Comment by Hayao0819** [comment]
この部分の処理だ。申し訳ない。

https://github.com/yamader/minskey/blob/de67cbf1151c448e479c1be1b9a31cd9f10c56ab/src/features/api/index.ts#L51
